function [w,wp,wpp,wppp]=wfu1(u,p) % arjens double well, p-param in p.pp
% NOT smooth at m_p
pp=p.pp; del=p.del;mp=(pp/2)^(1/(pp-2)); 
w=1/(pp-2)*(pp*(u+1).^2-2*(u+1).^pp)... %.*(u+1-mp-del<=0)...
    +20*(u+1-mp-del).^(p.pp+1).*(u+1-mp-del>0);
wp=2*pp/(pp-2)*((u+1)-(u+1).^(pp-1))... %.*(u+1-mp-del<=0)...
    +(pp+1)*20*(u+1-mp-p.del).^pp.*(u+1-mp-del>0);
wpp=2*pp/(pp-2)*(1-(pp-1)*(u+1).^(pp-2))...% .*(u+1-mp-del<=0)...
    +(pp+1)*pp*20*(u+1-mp-del).^(pp-1).*(u+1-mp-del>0);
wppp=-2*pp*(pp-1)*(u+1).^(pp-3)...% .*(u+1-mp-del<=0)...
    +(pp+1)*pp*(pp-1)*20*(u+1-mp-del).^(pp-2).*(u+1-mp-del>0);
end
